name: 'Deploy ECS'

on:
  workflow_run:
    workflows: ["Docker hub"]
    types:
      - completed
  workflow_dispatch:

jobs:
  sync:
    name: 'Deploy to ECS'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Debug - Verificar arquivos antes do build
      run: |
        echo "Verificando arquivos antes do build..."
        ls -l

    - name: Build, tag e push para o Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECS_TASK }}
        IMAGE_TAG: latest
      run: |
        echo "Iniciando build do Docker..."
        docker build -f Dockerfile.publish -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-arg ACF_KEY='${{ secrets.ACF_KEY }}' .
        
        echo "Fazendo push da imagem..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Debug - Verificar task-definition.json antes da substituição
      run: |
        echo "Listando arquivos para verificar task-definition.json"
        ls -l
        cat task-definition.json || echo "Arquivo task-definition.json não encontrado!"

    - name: Substituir variáveis no task-definition.json
      run: |
        sed -i 's/ECSTASK/${{ secrets.ECS_TASK }}/' task-definition.json
        sed -i 's/AWSACCID/${{ secrets.AWS_ACCOUNT_ID }}/' task-definition.json
        echo "Arquivo task-definition.json atualizado"

    - name: Preencher a nova imagem no Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ secrets.ECS_TASK }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Debug - Verificar task-definition.json após a substituição
      run: cat task-definition.json

    - name: Deploy para Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ secrets.ECS_TASK }}
        cluster: IASD
        wait-for-service-stability: true
